#encoders
Float64 FC_enc
Float64 FR_enc
Float64 MR_enc
Float64 ML_enc
Float64 ML_carr_enc
Float64 MR_carr_enc
Float64 ML_wheel_enc
Float64 MR_wheel_enc

#loacells
Float64 FC_lc
Float64 MR_lc
Float64 ML_lc

#states
Int64 ca_flag
String action

#VelAcc
Float64 ML_vel
Float64 MR_vel
Float64 ML_acc
Float64 MR_acc

#IMU
Float64 pitch
Float64 roll
Float64 ax
Float64 ay
Float64 az
Float64 tilt

#other
Float64 app_time
Float64 measure_height
