#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from std_msgs.msg import Bool
import keyboard


class EstopNode(Node):
    def __init__(self):
        super().__init__("estop_node")

        self.estop_publisher = self.create_publisher(Bool, "estop", 10)
        self.estop_timer = self.create_timer(1.0, self.estop_callback)
        self.estop_pressed = False

        keyboard.add_hotkey("q", self._on_press)

    def _on_press(self):
        self.estop_pressed = not self.estop_pressed

    def estop_callback(self):
        msg = Bool()
        msg.data = self.estop_pressed
        self.estop_publisher.publish(msg)


def main(args=None):
    rclpy.init()
    node = EstopNode()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    main()
