# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5.QtWidgets import (
    QMainWindow,
    QWidget,
    QLabel,
    QMenuBar,
    QStatusBar,
    QApplication,
)
from PyQt5.QtGui import QFont
from PyQt5.QtCore import QSize, QRect, QMetaObject, QCoreApplication, QTimer
from components.JoystickThread import JoystickThread
from components.Buttons import BaseButton, PushButton, NestedButton
import traceback

script_dir = os.path.dirname(os.path.realpath(__file__))
# Move one directory up
parent_dir = os.path.dirname(script_dir)
assets_dir = os.path.join(parent_dir, "assets/")

LOGS_PER_SEC = 100  # 100 logs every second or 100Hz sampling frequency

LOGGING_INTERVAL = 1000 // min(LOGS_PER_SEC, 1000)  # integer division, (1000ms = 1s)


class UserWindow(QMainWindow):
    def __init__(self, stacked_widget, teensy_controller, data_logger):
        super().__init__()
        self.stacked_widget = stacked_widget
        self.teensy_controller = teensy_controller

        # data logger
        self.logging = False
        self.data_logger = data_logger
        self.logger_timmer = QTimer()
        self.logger_timmer.timeout.connect(self.data_logger.log)

        # Intialize variables
        self.carriage_state = "Front-Wheel Drive"
        self.setupUi()

        # Start joystick monitoring thread
        self.joystick_thread = JoystickThread()
        self.joystick_thread.forward_signal.connect(self.handle_forward_movement)
        self.joystick_thread.reverse_signal.connect(self.handle_reverse_movement)
        self.joystick_thread.left_signal.connect(self.handle_left_movement)
        self.joystick_thread.right_signal.connect(self.handle_right_movement)

        # Connect the neutral signal to the function
        self.joystick_thread.neutral_signal.connect(self.handle_neutral_movement)
        self.joystick_thread.start()

    def to_dev_mode(self):
        try:
            # Set to Dev Screen (screen 1)
            self.stacked_widget.setCurrentIndex(1)
        except Exception as e:
            print("Error in to_dev_mode:", e)
            traceback.print_exc()

    def start_logging(self):
        self.data_logger.start()
        self.logger_timmer.start(LOGGING_INTERVAL)

    def stop_logging(self):
        if self.logging is False:
            return
        self.logger_timmer.stop()
        self.data_logger.stop()

    def handle_logging(self):
        if self.logging is False:
            self.log_data_btn.setText("Stop Log")
            self.log_data_btn.setBackgroundColor("LightRed")
            self.start_logging()
            self.logging = True
        else:
            self.log_data_btn.setText("Start Log")
            self.log_data_btn.setBackgroundColor("Default")
            self.stop_logging()
            self.logging = False

    def exit_screen(self):
        try:
            sender_button = self.sender()
            if sender_button == self.exitButton:
                # Cleanup on exit
                self.teensy_controller.reset()

                self.stop_logging()

                QApplication.quit()
        except Exception as e:
            print("Error in exit_screen:", e)
            traceback.print_exc()

    def setupUi(self):
        try:
            self.setObjectName("MainWindow")
            self.showFullScreen()
            # MainWindow.resize(870, 600)
            self.centralwidget = QWidget(self)
            self.centralwidget.setObjectName("centralwidget")
            self.setCentralWidget(self.centralwidget)

            # Define button objects
            # ##################################

            self.elevate_btn = PushButton(
                self.centralwidget,
                icon_path=f"{assets_dir}elevate.png",
                geometry=(45, 165, 105, 170),
            )
            self.elevate_btn.setBackgroundColor("LightBlue")

            self.raise_up_btn = NestedButton(
                self.elevate_btn,
                icon_path=f"{assets_dir}Up Arrow.png",
                geometry=(0, 0, 105, 35),
            )
            self.raise_up_btn.pressed.connect(self.teensy_controller.raise_up_pressed)
            self.raise_up_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            self.lower_down_btn = NestedButton(
                self.elevate_btn,
                icon_path=f"{assets_dir}Down Arrow.png",
                geometry=(0, 135, 105, 35),
            )
            self.lower_down_btn.pressed.connect(
                self.teensy_controller.lower_down_pressed
            )
            self.lower_down_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            # ##################################

            self.lean_btn = PushButton(
                self.centralwidget,
                icon_path=f"{assets_dir}lean.png",
                geometry=(165, 165, 105, 170),
            )

            self.lean_forward_btn = NestedButton(
                self.lean_btn,
                icon_path=f"{assets_dir}Right Arrow.png",
                geometry=(0, 0, 105, 35),
            )
            self.lean_forward_btn.pressed.connect(
                self.teensy_controller.tilt_forward_pressed
            )
            self.lean_forward_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            self.lean_backward_btn = NestedButton(
                self.lean_btn,
                icon_path=f"{assets_dir}Left Arrow.png",
                geometry=(0, 135, 105, 35),
            )
            self.lean_backward_btn.pressed.connect(
                self.teensy_controller.tilt_backward_pressed
            )
            self.lean_backward_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            # ##################################

            self.tilt_btn = PushButton(
                self.centralwidget,
                icon_path=f"{assets_dir}tilt.png",
                geometry=(285, 165, 105, 170),
            )

            self.tilt_left_btn = NestedButton(
                self.tilt_btn,
                icon_path=f"{assets_dir}Left Arrow.png",
                geometry=(0, 0, 105, 35),
            )
            self.tilt_left_btn.pressed.connect(self.teensy_controller.tilt_left_pressed)
            self.tilt_left_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            self.tilt_right_btn = NestedButton(
                self.tilt_btn,
                icon_path=f"{assets_dir}Right Arrow.png",
                geometry=(0, 135, 105, 35),
            )
            self.tilt_right_btn.pressed.connect(
                self.teensy_controller.tilt_right_pressed
            )
            self.tilt_right_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            # ##################################

            self.carriage_btn = PushButton(
                self.centralwidget,
                icon_path=f"{assets_dir}carriage.png",
                geometry=(405, 165, 105, 170),
            )

            self.carriage_forward_btn = NestedButton(
                self.carriage_btn,
                icon_path=f"{assets_dir}Left Arrow.png",
                geometry=(0, 0, 105, 35),
            )
            self.carriage_forward_btn.pressed.connect(self.carriage_forward_pressed)
            self.carriage_forward_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            self.carriage_backward_btn = NestedButton(
                self.carriage_btn,
                icon_path=f"{assets_dir}Right Arrow.png",
                geometry=(0, 135, 105, 35),
            )
            self.carriage_backward_btn.pressed.connect(self.carriage_backward_pressed)
            self.carriage_backward_btn.released.connect(
                self.teensy_controller.send_neutral_signal_to_teensy
            )

            # ##################################

            self.self_leveling_btn = PushButton(
                self.centralwidget,
                icon_path=f"{assets_dir}self_leveling.png",
                geometry=(525, 165, 105, 170),
            )
            self.self_leveling_btn.clicked.connect(
                self.teensy_controller.self_leveling_pressed
            )

            # ##################################

            self.curb_ascend_btn = PushButton(
                self.centralwidget, icon_path=None, geometry=(645, 165, 105, 170)
            )
            self.curb_ascend_btn.setIconSize(QSize(25, 25))

            self.curb_ascend_up_btn = NestedButton(
                self.curb_ascend_btn,
                icon_path=f"{assets_dir}curb_ascend.png",
                geometry=(0, 0, 105, 75),
            )
            self.curb_ascend_up_btn.setIconSize(QSize(65, 65))
            self.curb_ascend_up_btn.clicked.connect(
                self.teensy_controller.curb_climb_automation
            )

            self.curb_ascend_down_btn = NestedButton(
                self.curb_ascend_btn,
                icon_path=f"{assets_dir}curb_descend.png",
                geometry=(0, 95, 105, 75),
            )
            self.curb_ascend_down_btn.setIconSize(QSize(65, 65))
            self.curb_ascend_down_btn.clicked.connect(
                self.teensy_controller.curb_descend_automation
            )

            # ##################################

            self.reset_btn = BaseButton(
                self.centralwidget, geometry=(620, 365, 160, 80)
            )
            self.reset_btn.clicked.connect(self.teensy_controller.reset)

            # ##################################

            self.dev_mode_btn = BaseButton(
                self.centralwidget, geometry=(445, 365, 160, 80)
            )
            self.dev_mode_btn.clicked.connect(self.to_dev_mode)

            # ##################################

            self.log_data_btn = BaseButton(
                self.centralwidget, geometry=(20, 365, 160, 80)
            )
            self.log_data_btn.clicked.connect(self.handle_logging)

            # ##################################

            self.exitButton = BaseButton(self.centralwidget, geometry=(20, 10, 160, 80))
            self.exitButton.clicked.connect(self.exit_screen)

            # Initialize current_button attribute with 'Raise Up/Lower Down' button
            self.current_button = self.elevate_btn

            # # Label to display selected button
            # self.label = QtWidgets.QLabel(self.centralwidget)
            # self.label.setGeometry(QtCore.QRect(350, 10, 200, 30))
            # self.label.setObjectName("label")
            # self.label.setText("Current Button: None")

            # Label to display selected button
            self.carriage_label = QLabel(self.centralwidget)
            self.carriage_label.setGeometry(QRect(300, 20, 350, 30))
            self.carriage_label.setObjectName("carriage_label")
            self.carriage_label.setFont(QFont("Aptos", 12))
            self.carriage_label.setText("Current State: Front-Wheel Drive")

            self.menubar = QMenuBar(self)
            self.menubar.setGeometry(QRect(0, 0, 800, 20))
            self.menubar.setObjectName("menubar")
            self.setMenuBar(self.menubar)
            self.statusbar = QStatusBar(self)
            self.statusbar.setObjectName("statusbar")
            self.setStatusBar(self.statusbar)

            self.retranslateUi()
            QMetaObject.connectSlotsByName(self)

            # Initialize a flag to track if button color needs to be updated
            self.update_button_color_flag = False

        except Exception as e:
            print("Error in setupUI:", e)
            traceback.print_exc()

    def handle_neutral_movement(self):
        self.teensy_controller.send_neutral_signal_to_teensy()
        self.update_button_color_flag = True
        self.update_button_color("Neutral")

    def handle_forward_movement(self):
        try:
            # self.update_label_text() # Update label text after button change
            self.update_button_color_flag = True
            self.update_button_color("Forward")

            print("Forward joystick movement detected")
            if self.current_button == self.elevate_btn:
                self.teensy_controller.raise_up_pressed()
            elif self.current_button == self.lean_btn:
                self.teensy_controller.tilt_forward_pressed()
            elif self.current_button == self.tilt_btn:
                self.teensy_controller.tilt_left_pressed()
            elif self.current_button == self.carriage_btn:
                self.carriage_forward_pressed()
            elif self.current_button == self.curb_ascend_btn:
                self.teensy_controller.curb_climb_automation()
            elif self.current_button == self.self_leveling_btn:
                self.teensy_controller.self_leveling_pressed()
            elif self.current_button == self.reset_btn:
                self.teensy_controller.reset()
            elif self.current_button == self.dev_mode_btn:
                self.to_dev_mode()
        except Exception as e:
            print("Error in handle_forward_movement:", e)
            traceback.print_exc()

    def handle_reverse_movement(self):
        try:
            # self.update_label_text() # Update label text after button change
            self.update_button_color_flag = True
            self.update_button_color("Reverse")

            print("Reverse joystick movement detected")
            if self.current_button == self.elevate_btn:
                self.teensy_controller.lower_down_pressed()
            elif self.current_button == self.lean_btn:
                self.teensy_controller.tilt_backward_pressed()
            elif self.current_button == self.tilt_btn:
                self.teensy_controller.tilt_right_pressed()
            elif self.current_button == self.carriage_btn:
                self.carriage_backward_pressed()
            elif self.current_button == self.curb_ascend_btn:
                self.teensy_controller.reset()
            elif self.current_button == self.self_leveling_btn:
                self.teensy_controller.self_leveling_pressed()
            elif self.current_button == self.reset_btn:
                self.teensy_controller.reset()
            elif self.current_button == self.dev_mode_btn:
                self.to_dev_mode()
        except Exception as e:
            print("Error in handle_reverse_movement:", e)
            traceback.print_exc()

    def handle_left_movement(self):
        try:
            print("Left joystick movement detected")
            self.update_button_color_flag = True
            self.update_button_color("Left")
            # self.update_label_text() # Update label text after button change
        except Exception as e:
            print("Error in handle_left_movement:", e)
            traceback.print_exc()

    def handle_right_movement(self):
        try:
            print("Right joystick movement detected")
            self.update_button_color_flag = True
            self.update_button_color("Right")
            # self.update_label_text() # Update label text after button change
        except Exception as e:
            print("Error in handle_right_movement:", e)
            traceback.print_exc()

    def retranslateUi(self):
        try:
            _translate = QCoreApplication.translate
            self.setWindowTitle(_translate("MainWindow", "MainWindow"))
            self.elevate_btn.setText(_translate("MainWindow", ""))
            self.lean_btn.setText(_translate("MainWindow", ""))
            self.tilt_btn.setText(_translate("MainWindow", ""))
            self.carriage_btn.setText(_translate("MainWindow", ""))
            self.self_leveling_btn.setText(_translate("MainWindow", ""))
            self.curb_ascend_btn.setText(_translate("MainWindow", "Neutral"))
            self.curb_ascend_btn.setFont(QFont("Aptos", 12))
            self.reset_btn.setText(_translate("MainWindow", "Reset"))
            self.reset_btn.setFont(QFont("Aptos", 12))
            self.log_data_btn.setText(_translate("MainWindow", "Start Log"))
            self.log_data_btn.setFont(QFont("Aptos", 12))
            self.dev_mode_btn.setText(_translate("MainWindow", "Dev Mode"))
            self.dev_mode_btn.setFont(QFont("Aptos", 12))
            self.exitButton.setText(_translate("MainWindow", "Exit"))
            self.exitButton.setFont(QFont("Aptos", 12))
        except Exception as e:
            print("Error in retranslateUi:", e)
            traceback.print_exc()

    def update_button_color(self, direction):
        try:
            # Check if button color needs to be updated based on user input
            if not self.update_button_color_flag:
                return

            # Define the list of buttons in the order they should cycle
            buttons = [
                self.elevate_btn,
                self.lean_btn,
                self.tilt_btn,
                self.carriage_btn,
                self.self_leveling_btn,
                self.curb_ascend_btn,
                self.dev_mode_btn,
                self.reset_btn,
            ]

            # Get the index of the currently highlighted button
            current_index = buttons.index(self.current_button)

            if direction == "Neutral":
                pass
            elif direction == "Left":
                # Cycle left
                current_index = (current_index - 1) % len(buttons)
            elif direction == "Right":
                # Cycle right
                current_index = (current_index + 1) % len(buttons)
            elif direction == "Forward":
                # Set all buttons to default color
                for button in buttons:
                    button.setBackgroundColor("Default")

                # Set the color of the current nested_button to green
                if self.current_button == self.elevate_btn:
                    self.raise_up_btn.setBackgroundColor("LightGreen")
                    self.lower_down_btn.setBackgroundColor("Default")
                elif self.current_button == self.lean_btn:
                    self.lean_forward_btn.setBackgroundColor("LightGreen")
                    self.lean_backward_btn.setBackgroundColor("Default")
                elif self.current_button == self.tilt_btn:
                    self.tilt_left_btn.setBackgroundColor("LightGreen")
                    self.tilt_right_btn.setBackgroundColor("Default")
                elif self.current_button == self.carriage_btn:
                    self.carriage_forward_btn.setBackgroundColor("LightGreen")
                    self.carriage_backward_btn.setBackgroundColor("Default")
                elif self.current_button == self.self_leveling_btn:
                    self.self_leveling_btn.setBackgroundColor("LightRed")
                elif self.current_button == self.curb_ascend_btn:
                    self.curb_ascend_up_btn.setBackgroundColor("LightGreen")
                    self.curb_ascend_down_btn.setBackgroundColor("Default")
                elif self.current_button == self.reset_btn:
                    self.reset_btn.setBackgroundColor("LightRed")

                # Reset the flag after updating button color
                self.update_button_color_flag = False
                return
            elif direction == "Reverse":
                # Set all buttons to default color
                for button in buttons:
                    button.setBackgroundColor("Default")

                # Set the color of the current nested_button to green
                if self.current_button == self.elevate_btn:
                    self.raise_up_btn.setBackgroundColor("Default")
                    self.lower_down_btn.setBackgroundColor("LightYellow")
                elif self.current_button == self.lean_btn:
                    self.lean_forward_btn.setBackgroundColor("Default")
                    self.lean_backward_btn.setBackgroundColor("LightYellow")
                elif self.current_button == self.tilt_btn:
                    self.tilt_left_btn.setBackgroundColor("Default")
                    self.tilt_right_btn.setBackgroundColor("LightYellow")
                elif self.current_button == self.carriage_btn:
                    self.carriage_forward_btn.setBackgroundColor("Default")
                    self.carriage_backward_btn.setBackgroundColor("LightYellow")
                elif self.current_button == self.self_leveling_btn:
                    self.self_leveling_btn.setBackgroundColor("LightRed")
                elif self.current_button == self.curb_ascend_btn:
                    self.curb_ascend_up_btn.setBackgroundColor("Default")
                    self.curb_ascend_down_btn.setBackgroundColor("LightYellow")
                elif self.current_button == self.reset_btn:
                    self.reset_btn.setBackgroundColor("LightRed")

                # Reset the flag after updating button color
                self.update_button_color_flag = False
                return

            # Reset all buttons to default color
            for button in buttons:
                button.setBackgroundColor("Default")
            self.raise_up_btn.setBackgroundColor("Default")
            self.lower_down_btn.setBackgroundColor("Default")
            self.lean_forward_btn.setBackgroundColor("Default")
            self.lean_backward_btn.setBackgroundColor("Default")
            self.tilt_left_btn.setBackgroundColor("Default")
            self.tilt_right_btn.setBackgroundColor("Default")
            self.carriage_forward_btn.setBackgroundColor("Default")
            self.carriage_backward_btn.setBackgroundColor("Default")
            self.curb_ascend_up_btn.setBackgroundColor("Default")
            self.curb_ascend_down_btn.setBackgroundColor("Default")

            # Set the color of the button corresponding to the updated index
            buttons[current_index].setBackgroundColor("LightBlue")

            # Update the current button
            self.current_button = buttons[current_index]

            # Reset the flag after updating button color
            self.update_button_color_flag = False

            # Debug statement to print the index of the button being selected
            print("Navigating to button:", current_index)

        except Exception as e:
            print("Error in update_button_color:", e)
            traceback.print_exc()

    def carriage_backward_pressed(self):
        try:
            if self.carriage_state == "Rear-Wheel Drive":
                self.carriage_state = "Rear-Wheel Drive"
            elif self.carriage_state == "Mid-Wheel Drive":
                self.carriage_state = "Rear-Wheel Drive"
            elif self.carriage_state == "Front-Wheel Drive":
                self.carriage_state = "Mid-Wheel Drive"

            self.teensy_controller.carriage_backward_pressed()

            self.carriage_label.setText("Carriage State: " + self.carriage_state)

        except Exception as e:
            print("Error in carriage_forward_and_backward_pressed:", e)
            traceback.print_exc()

    def carriage_forward_pressed(self):
        try:
            if self.carriage_state == "Rear-Wheel Drive":
                self.carriage_state = "Mid-Wheel Drive"
            elif self.carriage_state == "Mid-Wheel Drive":
                self.carriage_state = "Front-Wheel Drive"
            elif self.carriage_state == "Front-Wheel Drive":
                self.carriage_state = "Front-Wheel Drive"

            self.teensy_controller.carriage_forward_pressed()

            self.carriage_label.setText("Carriage State: " + self.carriage_state)

        except Exception as e:
            print("Error in carriage_forward_and_backward_pressed:", e)
            traceback.print_exc()
